-- The Report
SELECT (CASE WHEN Grades.Grade < 8 THEN 'NULL' ELSE Students.Name END ), GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS JOIN GRADES ON GRADES.MAX_MARK >= STUDENTS.MARKS AND STUDENTS.MARKS >= GRADES.MIN_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME, MARKS;